version: '3.8'
name: people-service

services:
  api1:
    image: people-service:latest
    hostname: api1
    environment:
      - SERVER_PORT=8000
      - DATABASE_URL=jdbc:postgresql://postgres:5432/postgres_db?currentSchema=public
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

      - HIKARI_CONNECTION_TIMEOUT=40000
      - HIKARI_MAXIMUM_POOL_SIZE=250
      - HIKARI_MINIMUM_IDLE=20
      - REDIS_HOST=cache
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.7GB'
    networks:
      - app-network

  api2:
    image: people-service:latest
    hostname: api2
    environment:
      - SERVER_PORT=8000
      - DATABASE_URL=jdbc:postgresql://postgres:5432/postgres_db?currentSchema=public
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

      - HIKARI_CONNECTION_TIMEOUT=40000
      - HIKARI_MAXIMUM_POOL_SIZE=250
      - HIKARI_MINIMUM_IDLE=20
      - REDIS_HOST=cache
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.7GB'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.50GB'
    networks:
      - app-network

  redis:
    hostname: cache
    image: redis:latest
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.50GB'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - app-network

  postgres:
    image: postgres:latest
    command: postgres -c 'max_connections=600'
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '0.7'
          memory: '1.5GB'
    networks:
      - app-network

networks:
  app-network: