server:
  port: 8000
  compression:
    enabled: true
    min-response-size: 1024
spring:
  ##
  # DataSource and JPA/Hibernate (PostgreSQL)
  ##
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres_db?currentSchema=public}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      auto-commit: false
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:10}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:10000}
      minimum-idle: ${HIKARI_MINIMUM_IDLE:10}
      schema: public
  jpa:
    generate-ddl: false
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false